"""add face enrollment and face models

Revision ID: 83a1ecd33664
Revises: 216b16a1e6ec
Create Date: 2026-09-26 00:09:01.754023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a1ecd33664'
down_revision: Union[str, Sequence[str], None] = '216b16a1e6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_models_algorithm'), 'face_models', ['algorithm'], unique=False)
    op.create_index(op.f('ix_face_models_is_active'), 'face_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_face_models_organization_id'), 'face_models', ['organization_id'], unique=False)
    op.create_table('face_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('capture_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_enrollments_status'), 'face_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_face_enrollments_student_id'), 'face_enrollments', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_enrollments_student_id'), table_name='face_enrollments')
    op.drop_index(op.f('ix_face_enrollments_status'), table_name='face_enrollments')
    op.drop_table('face_enrollments')
    op.drop_index(op.f('ix_face_models_organization_id'), table_name='face_models')
    op.drop_index(op.f('ix_face_models_is_active'), table_name='face_models')
    op.drop_index(op.f('ix_face_models_algorithm'), table_name='face_models')
    op.drop_table('face_models')
    # ### end Alembic commands ###
